name: 'Ensure there is a valid changeset entry for each package'
description: 'Fail if there is not a valid changeset entry for each package.'
author: 'Ned Redmond'

inputs:
  changed_files:
    description: JSON list of changed files
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Veryify changeset entries
      uses: ./actions/verify-per-package
      with:
        changed_files: ${{ inputs.changed_files }}
