name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: yarn

      - name: Install Dependencies
        id: yarn-ci
        run: yarn install --frozen-lockfile

      - name: Check Format
        id: yarn-format-check
        run: yarn format:check

      - name: Lint
        id: yarn-lint
        run: yarn lint

      - name: Test
        id: yarn-ci-test
        run: yarn ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        uses: Khan/actions@get-changed-files-v1
        id: changed

      - name: Filter out files that don't need a changeset
        uses: Khan/actions@filter-files-v0
        id: match
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          invert: true

      - name: Verify changeset entries
        uses: ./
        with:
          changed_files: ${{ steps.match.outputs.filtered }}
